name: Windows

on:
  push:
    branches:
      - main
  pull_request:

env:
  MQTT_BROKER_URI: ${{ secrets.MQTT_BROKER_URI }}
  MQTT_BROKER_PORT: ${{ secrets.MQTT_BROKER_PORT }}
  KAFKA_BROKER_URI: ${{ secrets.KAFKA_BROKER_URI }}
  KAFKA_TOPIC_PREFIX: ${{ secrets.KAFKA_TOPIC_PREFIX }}
  KAFKA_SASL_MECHANISM: ${{ secrets.KAFKA_SASL_MECHANISM }}
  KAFKA_SECURITY_PROTOCOL: ${{ secrets.KAFKA_SECURITY_PROTOCOL }}
  KAFKA_USERNAME: ${{ secrets.KAFKA_USERNAME }}
  KAFKA_PASSWORD: ${{ secrets.KAFKA_PASSWORD }}

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Server 2019 [Release]",
            os: windows-2019,
            build-type: "Release",
            vcpkg-deps: "mosquitto:x64-windows rapidjson:x64-windows librdkafka:x64-windows"
          }
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache/Restore Dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
          path: |
            C:/vcpkg/buildtrees
            C:/vcpkg/installed
            C:/vcpkg/packages
          key: vcpkg--${{matrix.config.os}}

    - name: Set Up Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: vcpkg install ${{matrix.config.vcpkg-deps}}

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake ${{runner.workspace}}/opera -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake -DMQTT_HOST="broker.emqx.io"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel --config ${{matrix.config.build-type}}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest --output-on-failure -E kafka